# RTTE mission toml file
#
# LayerIndex
#   Defines the order in which entities will be rendered.
#   Entities are z-indexed within the same layer.
#
# Polygon
#   Entity shape.
#   Points are relative to Position.
#
# Position
#   Entity position.
#
# Size
#   Entity size.
#
# TexturePath
#   Texture file path.
#   Relative to this file.
#   It will fill the entire polygon. If the texture is smaller it will be repeated in both axes.
#

[[Entities]]
LayerIndex = 0
Polygon = [[0, 0], [100, 300], [200, 300], [100, 0]]
Position = [100, 100]
Size = [200, 300]
TexturePath = "textures/grass.png"

[[Entities]]
LayerIndex = 0
Polygon = [[0, 0], [100, 300], [200, 300], [100, 0]]
Position = [200, 100]
Size = [200, 300]
TexturePath = "textures/snow.png"

[[Entities]]
LayerIndex = 0
Polygon = [[0, 0], [100, 300], [200, 300], [100, 0]]
Position = [300, 100]
Size = [200, 300]
TexturePath = "textures/water.png"

[[Entities]]
LayerIndex = 1
Polygon = [[0, 0], [100, 300], [200, 300], [100, 0]]
Position = [400, 100]
Size = [200, 300]
TexturePath = "textures/sand.png"
