[mesh.rect]
x = 0.0
y = 0.0
w = 800.0
h = 600.0

[[mesh.vectors]]
x = 0.0
y = 0.0

[[mesh.vectors]]
x = 800.0
y = 0.0

[[mesh.vectors]]
x = 800.0
y = 600.0

[[mesh.vectors]]
x = 0.0
y = 600.0

[[mesh.vectors]]
x = 230.0
y = 103.0

[[mesh.vectors]]
x = 254.0
y = 82.0

[[mesh.vectors]]
x = 267.0
y = 100.0

[[mesh.vectors]]
x = 242.0
y = 116.0

[[mesh.triangles]]
is_path_block = true
is_view_block = true

[mesh.triangles.a]
x = 267.0
y = 100.0

[mesh.triangles.b]
x = 254.0
y = 82.0

[mesh.triangles.c]
x = 242.0
y = 116.0

[[mesh.triangles]]
is_path_block = true
is_view_block = true

[mesh.triangles.a]
x = 254.0
y = 82.0

[mesh.triangles.b]
x = 230.0
y = 103.0

[mesh.triangles.c]
x = 242.0
y = 116.0

[[mesh.triangles]]
is_path_block = false
is_view_block = false

[mesh.triangles.a]
x = 254.0
y = 82.0

[mesh.triangles.b]
x = 0.0
y = 0.0

[mesh.triangles.c]
x = 230.0
y = 103.0

[[mesh.triangles]]
is_path_block = false
is_view_block = false

[mesh.triangles.a]
x = 230.0
y = 103.0

[mesh.triangles.b]
x = 0.0
y = 600.0

[mesh.triangles.c]
x = 242.0
y = 116.0

[[mesh.triangles]]
is_path_block = false
is_view_block = false

[mesh.triangles.a]
x = 0.0
y = 0.0

[mesh.triangles.b]
x = 0.0
y = 600.0

[mesh.triangles.c]
x = 230.0
y = 103.0

[[mesh.triangles]]
is_path_block = false
is_view_block = false

[mesh.triangles.a]
x = 242.0
y = 116.0

[mesh.triangles.b]
x = 800.0
y = 600.0

[mesh.triangles.c]
x = 267.0
y = 100.0

[[mesh.triangles]]
is_path_block = false
is_view_block = false

[mesh.triangles.a]
x = 254.0
y = 82.0

[mesh.triangles.b]
x = 800.0
y = 0.0

[mesh.triangles.c]
x = 0.0
y = 0.0

[[mesh.triangles]]
is_path_block = false
is_view_block = false

[mesh.triangles.a]
x = 267.0
y = 100.0

[mesh.triangles.b]
x = 800.0
y = 0.0

[mesh.triangles.c]
x = 254.0
y = 82.0

[[mesh.triangles]]
is_path_block = false
is_view_block = false

[mesh.triangles.a]
x = 800.0
y = 600.0

[mesh.triangles.b]
x = 800.0
y = 0.0

[mesh.triangles.c]
x = 267.0
y = 100.0

[[mesh.triangles]]
is_path_block = false
is_view_block = false

[mesh.triangles.a]
x = 0.0
y = 600.0

[mesh.triangles.b]
x = 800.0
y = 600.0

[mesh.triangles.c]
x = 242.0
y = 116.0

[[mesh.pov_barriers]]

[mesh.pov_barriers.a]
x = 267.0
y = 100.0

[mesh.pov_barriers.b]
x = 254.0
y = 82.0

[[mesh.pov_barriers]]

[mesh.pov_barriers.a]
x = 254.0
y = 82.0

[mesh.pov_barriers.b]
x = 242.0
y = 116.0

[[mesh.pov_barriers]]

[mesh.pov_barriers.a]
x = 242.0
y = 116.0

[mesh.pov_barriers.b]
x = 267.0
y = 100.0

[[mesh.pov_barriers]]

[mesh.pov_barriers.a]
x = 254.0
y = 82.0

[mesh.pov_barriers.b]
x = 230.0
y = 103.0

[[mesh.pov_barriers]]

[mesh.pov_barriers.a]
x = 230.0
y = 103.0

[mesh.pov_barriers.b]
x = 242.0
y = 116.0

[[mesh.pov_barriers]]

[mesh.pov_barriers.a]
x = 242.0
y = 116.0

[mesh.pov_barriers.b]
x = 254.0
y = 82.0

[[characters]]

[characters.pos]
x = 300.0
y = 75.0

[characters.size]
x = 10.0
y = 10.0

[[enemies]]
res_path = "/enemy.png"

[enemies.pos]
x = 172.89569091796875
y = 245.7911834716797

[enemies.size]
x = 10.0
y = 23.0

[[enemies.path_default]]
x = 100.0
y = 100.0

[[enemies.path_default]]
x = 200.0
y = 300.0

[[objects]]
res_path = "/barrels.png"

[objects.pos]
x = 250.0
y = 100.0

[objects.size]
x = 36.0
y = 32.0
