####################################################################################################
# players

[[player]]
image = "resources/player-sprite.png"
position = [24, 24]
# TODO: collider width
# TODO: collider height

[player.animation]
direction = "E"
frame_delay = 10
frame_height = 48
frame_width = 48

# [player.animation.idle]
# directions = ["S", "SW", "W", "NW", "N", "NE", "E", "SE"]
# frame_row = 8

[player.animation.walk]
directions = ["S", "SW", "W", "NW", "N", "NE", "E", "SE"]
frame_row = 0

# [player.animation.run]
# directions = ["S", "SW", "W", "NW", "N", "NE", "E", "SE"]
# frame_row = 16

# [player.animation.crawl]
# directions = ["S", "SW", "W", "NW", "N", "NE", "E", "SE"]
# frame_row = 16

[[player]]
image = "resources/player-sprite.png"
position = [75, 24]
# TODO: collider width
# TODO: collider height

[player.animation]
direction = "S"
frame_delay = 10
frame_height = 48
frame_width = 48

# [player.animation.idle]
# directions = ["S", "SW", "W", "NW", "N", "NE", "E", "SE"]
# frame_row = 8

[player.animation.walk]
directions = ["S", "SW", "W", "NW", "N", "NE", "E", "SE"]
frame_row = 0

# [player.animation.run]
# directions = ["S", "SW", "W", "NW", "N", "NE", "E", "SE"]
# frame_row = 16

# [player.animation.crawl]
# directions = ["S", "SW", "W", "NW", "N", "NE", "E", "SE"]
# frame_row = 24

####################################################################################################
# enemies

[[enemy]]
field_of_view_direction = 0
image = "resources/enemy-sprite.png"
path = [[550, 400], [650, 500], [450, 500], [450, 400]]
position = [450, 400]

[enemy.animation]
direction = "E"
frame_delay = 10
frame_height = 48
frame_width = 48

# [enemy.animation.idle]
# directions = ["S", "SW", "W", "NW", "N", "NE", "E", "SE"]
# frame_row = 8

[enemy.animation.walk]
directions = ["S", "SW", "W", "NW", "N", "NE", "E", "SE"]
frame_row = 0

# [enemy.animation.run]
# directions = ["S", "SW", "W", "NW", "N", "NE", "E", "SE"]
# frame_row = 16

# [enemy.animation.crawl]
# directions = ["S", "SW", "W", "NW", "N", "NE", "E", "SE"]
# frame_row = 24

[[enemy]]
field_of_view_direction = 4.7123
image = "resources/enemy-sprite.png"
path = []
position = [350, 475]

[enemy.animation]
direction = "N"
frame_delay = 10
frame_height = 48
frame_width = 48

# [enemy.animation.idle]
# directions = ["S", "SW", "W", "NW", "N", "NE", "E", "SE"]
# frame_row = 8

[enemy.animation.walk]
directions = ["S", "SW", "W", "NW", "N", "NE", "E", "SE"]
frame_row = 0

# [enemy.animation.run]
# directions = ["S", "SW", "W", "NW", "N", "NE", "E", "SE"]
# frame_row = 16

# [enemy.animation.crawl]
# directions = ["S", "SW", "W", "NW", "N", "NE", "E", "SE"]
# frame_row = 24

####################################################################################################
# objects
#
# object shape must be a convex polgyon
# object shape points are relative to object position
# object shape points are clockwise ordered

[[object]]
image = "resources/ground.png"
position = [0, 0]
shape = [[0, 0], [800, 0], [800, 600], [0, 600]]
type = "none"
ysorted = false

[[object]]
image = "resources/block-001.png"
position = [300, 300]
shape = [[50, 52], [60, 59], [13, 90], [0, 83]]
type = "block"
ysorted = true

[[object]]
image = "resources/block-002.png"
position = [349, 342]
shape = [[-22, 38], [60, 82], [49, 89], [-36, 48]]
type = "block"
ysorted = true
