[[player]]
image = "/player.png"
position = [1, 1]

[[player]]
image = "/player.png"
position = [30, 1]

[[enemy]]
image = "/enemy.png"
path = [[550, 400], [650, 500], [450, 500], [450, 400]]
position = [450, 400]
view_direction = 0

[[enemy]]
image = "/enemy.png"
path = []
position = [350, 475]
view_direction = 4.7123

[[object]]
image = "/ground.png"
polygon = [[0, 0], [800, 0], [800, 600], [0, 600]]
polygon_type = "ground"
position = [0, 0]

[[object]]
image = "/block-001.png"
polygon = [[0, 83], [48, 107], [60, 101], [26,82], [60, 65], [48, 59]]
polygon_type = "block"
position = [300, 300]

[[object]]
image = "/block-002.png"
polygon = [[0,66], [49, 90], [60, 84], [11, 60]]
polygon_type = "block"
position = [349, 342]
