[[player]]
image = "resources/player.png"
position = [1, 1]

[[player]]
image = "resources/player.png"
position = [30, 1]

[[enemy]]
image = "resources/enemy.png"
path = [[550, 400], [650, 500], [450, 500], [450, 400]]
position = [450, 400]
view_direction = 0

[[enemy]]
image = "resources/enemy.png"
path = []
position = [350, 475]
view_direction = 4.7123

[[image]]
path = "resources/ground.png"
position = [0, 0]
ysorted = false

[[image]]
path = "resources/block-001.png"
position = [300, 300]
ysorted = true

[[image]]
path = "resources/block-002.png"
position = [349, 342]
ysorted = true

[[polygon]]
points = [[350, 352], [360, 359], [325, 380], [409, 424], [398, 431], [300, 383]]
type = "block"
