pub const DEBUG: bool = true;
pub const WINDOW_WIDTH: i32 = 800;
pub const WINDOW_HEIGHT: i32 = 600;
pub const PAN_SPEED: f32 = 5.;
pub const MIN_MOVEMENT_DISTANCE: f32 = 1.;
pub const RADIAN: f32 = std::f32::consts::PI / 180.;
pub const VIEW_DISTANCE: f32 = 150.;
pub const VIEW_INNER_ANGLE: f32 = 60. * RADIAN;
pub const VIEW_SHIFT_MAX_ANGLE: f32 = 30. * RADIAN;
